[package]
name = "nvim-gtk"
version = "0.3.0"
authors = ["daa84 <daa84@inbox.ru>"]
build = "build.rs"
edition = "2018"
license = "GPLv3"

[dependencies]
clap = "2.0"
cairo-rs = "0.15.0"
pango-sys = "0.15.0"
pangocairo = "0.15.0"
pangocairo-sys = "0.15.0"
glib = "0.15.0"
glib-sys = "0.15.0"
gdk = "0.15.0"
gdk-sys = "0.15.0"
gio = "0.15.0"
gobject-sys = "0.15.0"
async-trait = "0.1.0"
futures = { version = "0.3.0", features = ["io-compat", "thread-pool"] }
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.6.0", features = ["full"] }
nvim-rs = { version = "0.4.0", features = ["use_tokio"] }
phf = "0.10.0"
log = "0.4.0"
env_logger = "0.7.0"
htmlescape = "0.3.0"
rmpv = { version = "1.0", features = ["with-serde"] }
percent-encoding = "1.0"
regex = "1.0"
lazy_static = "1.0"
unicode-width = "0.1.0"
unicode-segmentation = "1.0"
fnv = "1.0"

serde = "1.0"
serde_derive = "1.0"
toml = "0.5.0"
serde_json = "1.0"

atty = "0.2.0"
dirs = "4.0"

[target.'cfg(unix)'.dependencies]
unix-daemonize = "0.1.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.0"

[build-dependencies]
phf_codegen = "0.10.0"
build-version = "0.1.1"

[dependencies.pango]
features = ["v1_46"]
version = "0.15.0"

[dependencies.gtk]
version = "0.15.0"
features = ["v3_24"]

[dependencies.gtk-sys]
version = "0.15.0"
features = ["v3_24"]
