[package]
name = "nvim-gtk"
version = "0.3.0"
authors = ["daa84 <daa84@inbox.ru>"]
build = "build.rs"
edition = "2018"
license = "GPLv3"

[dependencies]
clap = "2"
cairo-rs = "0.7"
pango-sys = "0.9"
pangocairo = "0.8"
pangocairo-sys = "0.10"
glib = "0.8.0"
glib-sys = "0.9"
gdk = "0.11"
gdk-sys = "0.9"
gio = "0.7.0"
gobject-sys = "0.9"
async-trait = "0.1"
futures = { version = "0.3", features = ["io-compat", "thread-pool"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["full"] }
nvim-rs = { version = "0.3", features = ["use_tokio"] }
phf = "0.10"
log = "0.4"
env_logger = "0.7"
htmlescape = "0.3"
rmpv = { version = "1", features = ["with-serde"] }
percent-encoding = "1"
regex = "1"
lazy_static = "1"
unicode-width = "0.1"
unicode-segmentation = "1"
fnv = "1"

serde = "1"
serde_derive = "1"
toml = "0.5"
serde_json = "1"

atty = "0.2"
dirs = "4"

whoami = "1"

[target.'cfg(unix)'.dependencies]
unix-daemonize = "0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[build-dependencies]
phf_codegen = "0.10"
build-version = "0.1.1"

[dependencies.pango]
features = ["v1_38"]
version = "0.7"

[dependencies.gtk]
version = "0.7"
features = ["v3_22"]

[dependencies.gtk-sys]
version = "0.9"
features = ["v3_22"]
